### PR TITLE
BUG: Tolerance on conservative check

### PR DESCRIPTION
**Pull request by cpelley**
Arbitrarily chosen tolerance value (1e-6)

### CODE REVIEW

**Comment by pelson** [comment]
Could you give a bit more context as to the bug you're fixing (nothing long, just some rationale / how the bug is manifesting)? Also, might be worth pulling out the magic (arbitrarily chosen) constant out to the module level, so that it can at least be monkey patched (and named)

**Comment by cpelley** [comment]
Hi @pelson .  Sorry, your quite right.
This issue relates to floating point precision of input coordinates.  One example manifestation might be that the source vertical coordinate (altitude) has been defined explicitly from NetCDF, but the target coordinates have have been derived (hybrid height coordinates) from pp.  In this case, if the target upper and/or lower extend matches the source extent, then this issue might present due to precision differences.

I uncovered this accidentally going from an 'identical' source and target coordinates.
Now that I think about it, I should also make stratify avoid doing any calculations where the source and target coordinates are the same (within precision) I think.
**What do you think?** - I was going to put this logic in our calling code but I don't see benefit in anyone using stratify having their own check for source-target equality.

> ...pulling out the magic... constant out to the module level, so that it can at least be monkey patched (and named)

Good idea!
I'm going to change this value to `1e-10` too (this would be in line with floating point tolerance we use elsewhere in our project and is likely safer).

**Comment by cpelley** [comment]
Do you have any ideas on how to implement the model level tolerance constant?
I was thinking it should be part of the python module `stratify._bounded_vinterp.py` (which calls `_conservative.pyx`) or potentially even `stratify.__init__.py`.  This would mean it could readily be monkey-patched.  Unfortunately, this would then require circular imports as far as I can tell :(
I think I'm being a little dim here - perhaps I'm being too strict or I'm missing something obvious?

Thanks @pelson

**Comment by bjlittle** [comment]
@cpelley Why not just keep things simple and make it a local constant within `_conservative.pyx`?

That provides a sufficient hook to monkey-patch for those that want to, right?

**Comment by cpelley** [comment]
> @cpelley Why not just keep things simple and make it a local constant within `_conservative.pyx`?
> 
> That provides a sufficient hook to monkey-patch for those that want to, right?

Oh I did wonder if I was missing a trick - I didn't think this would work since the cython was compiled so didn't think it would pick-up/allow objects (even if Python ones) within that module namespace!
I'm sure you're right.  I'll have a play.

Thanks @bjlittle

**Comment by cpelley** [comment]
I'm afraid I couldn't get this working :(
Couldn't see the variable from python
`cpdef FLOAT_TOLERANCE = 1e-10`

My limited knowledge of cython could be the trouble??
In either case, monkey patching the variable - would this would effect the performance of the cython code? (not being strictly a C variable).

**Comment by pelson** [comment]
> My limited knowledge of cython could be the trouble??

Define the constant as a Python variable in the module (no need for cpdef). Define a float variable inside apply_weights, and assign it from the Python constant. Use the float variable inside the loop. You get a runtime definition of the constant, but only pay the cost of the cast once. Hopefully that should do the trick 🤞

**Comment by cpelley** [comment]
Thanks @pelson works now.
I have also added an associated test to convince myself that it works as intended and can indeed be monkey-patched.

Cheers

**Comment by bjlittle** [comment]
@cpelley This is still needed?

**Comment by cpelley** [comment]
Thanks for the ping @bjlittle.  I'm afraid I am no longer involved in the work that motivated this issue so I couldn't be sure, though I would suspect that it is.

I'll close for now and ping @hdyson, @arjclark in case they want to pick this up again.

**Pull request closed without merging**
