### PR TITLE
BUG: Fixed bounds checking

### LINKED ISSUE #14: BUG: Axis compute in absolute terms
I originally put up a PR with iris [here](https://github.com/SciTools/iris/pull/2532) relating to tests which failed for me.
Now that I'm looking at the stratify implementation itself, I think I see a bug here in the checks conducted on the axis term which I suspect is where the real problem resides.

```Python
        # Compute the axis in absolute terms.
        fp_axis = (axis + fz_src.ndim) % fz_src.ndim
        zp_axis = fp_axis - (fz_src.ndim - z_src.ndim)
        if not 0 <= zp_axis < z_src.ndim or axis > z_src.ndim:
            raise ValueError('Axis {} out of range.'.format(axis))
```

[_Interpolation.\_\_init\_\_ here](https://github.com/SciTools-incubator/python-stratify/blob/12a556afe30880b1ba175afeaed6d2e78431f468/stratify/_vinterp.pyx#L551)

Specifically `axis > z_src.ndim` must be wrong surely??  `axis` is relative to `fz_src` not `z_src`.  To make this check valid, instead I would expect to see `zp_axis > z_src.ndim`.

I'm more than happy with fixing this myself if confirmed as a bug :)

### PR DESCRIPTION
**Pull request by cpelley**
closes #14 
Ideally a release might be a good idea following this, enabling https://github.com/SciTools/iris/pull/2532 to be merged also.

### CODE REVIEW

**Comment by cpelley** [comment]
FYI @hdyson @jkettleb

**Comment by hdyson** [comment]
@pelson @bjlittle I hope I'm not treading on your toes here - @cpelley has asked me to take a look at this to ease the review process.

I've four comments, of which the last is pretty trivial:

1. I think the logic in the second half of the conditional may be wrong: shouldn't `axis > fz_src.ndim` be `axis >= fz_src.ndim`?
2. The error message could be clearer.  It reports that the user-supplied axis is out of range (which is good), but could explain what the allowed range is.  Something like `"Axis {} out of range for source of dimension {}".format(axis, z_src.ndim)`, perhaps?
3. The absence of a test that fails without the code change is worth remarking on.  I'm not sure the extra test is justified, so it's your call, I just wanted to draw your attention to it.
4. Do the brackets in the conditional make it any easier to read?  Adding an extra set may make the operator stand out more, e.g.  `(not 0 <= zp_axis < z_src.ndim) or (axis > fz_src.ndim)`, but it's a personal taste thing really.  I'd be inclined to drop the brackets entirely.

**Comment by cpelley** [comment]
Thanks @hdyson 

All done except the exception message.  The context of the exception relates not necessarily to just z_src but also to fz_src and z_target.  This means splitting up the constraint into two to raise two different messages, one of which can only cause further confusion by explaining the relative axis number and how that relates to the axis the user provides...  I think in this case, it might be easier for the user to look at the docstring to understand their folly with their axis provided.  Are you happy with this?

**Comment by hdyson** [comment]
>  Are you happy with this?

Yes, of course.  You're right about having to split the conditional to yield better error messages.  It may still be a path to consider if people trip over it in future - but it makes sense to me to wait and see if anyone does fall over and needs to raise an issue rather than solve the problem themselves.

**Comment by cpelley** [comment]
Thanks @hdyson

**Comment by pelson** [comment]
> @pelson @bjlittle I hope I'm not treading on your toes here - @cpelley has asked me to take a look at this to ease the review process.

Definitely not. Steel toe-caps 😄. Seriously though, it is awesome to have somebody review the change objectively in the way you have. It builds confidence in the quality of the PR, and ultimately makes it easier to merge, so please keep contributing in this way! 👍

**Comment by cpelley** [comment]
Thanks @hdyson @pelson

**Pull request merged**
